server:
    applicationConnectors:
        - type: http
          port: 8085
database:
    #driverClass: com.postgresql.jdbc.driver
    driverClass: org.postgresql.Driver
    user: postgres
    password: agile
    url: jdbc:postgresql://localhost:5432/dropBookmarks
    #configurazione per hibernate
    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect